// AUTO-GENERATED by scripts/build-atlas.mjs - do not edit by hand.
export const frames = [
  {
    "filename": "bedrock.png",
    "frame": {
      "x": 1,
      "y": 1,
      "w": 16,
      "h": 16
    },
    "rotated": false,
    "trimmed": false,
    "spriteSourceSize": {
      "x": 0,
      "y": 0,
      "w": 16,
      "h": 16
    },
    "sourceSize": {
      "w": 16,
      "h": 16
    }
  },
  {
    "filename": "coal_ore.png",
    "frame": {
      "x": 19,
      "y": 1,
      "w": 16,
      "h": 16
    },
    "rotated": false,
    "trimmed": false,
    "spriteSourceSize": {
      "x": 0,
      "y": 0,
      "w": 16,
      "h": 16
    },
    "sourceSize": {
      "w": 16,
      "h": 16
    }
  },
  {
    "filename": "diamond_ore.png",
    "frame": {
      "x": 37,
      "y": 1,
      "w": 16,
      "h": 16
    },
    "rotated": false,
    "trimmed": false,
    "spriteSourceSize": {
      "x": 0,
      "y": 0,
      "w": 16,
      "h": 16
    },
    "sourceSize": {
      "w": 16,
      "h": 16
    }
  },
  {
    "filename": "dirt_block.png",
    "frame": {
      "x": 55,
      "y": 1,
      "w": 16,
      "h": 16
    },
    "rotated": false,
    "trimmed": false,
    "spriteSourceSize": {
      "x": 0,
      "y": 0,
      "w": 16,
      "h": 16
    },
    "sourceSize": {
      "w": 16,
      "h": 16
    }
  },
  {
    "filename": "gold_ore.png",
    "frame": {
      "x": 73,
      "y": 1,
      "w": 16,
      "h": 16
    },
    "rotated": false,
    "trimmed": false,
    "spriteSourceSize": {
      "x": 0,
      "y": 0,
      "w": 16,
      "h": 16
    },
    "sourceSize": {
      "w": 16,
      "h": 16
    }
  },
  {
    "filename": "grass_block_side.png",
    "frame": {
      "x": 91,
      "y": 1,
      "w": 16,
      "h": 16
    },
    "rotated": false,
    "trimmed": false,
    "spriteSourceSize": {
      "x": 0,
      "y": 0,
      "w": 16,
      "h": 16
    },
    "sourceSize": {
      "w": 16,
      "h": 16
    }
  },
  {
    "filename": "grass_block_side_snowed.png",
    "frame": {
      "x": 109,
      "y": 1,
      "w": 16,
      "h": 16
    },
    "rotated": false,
    "trimmed": false,
    "spriteSourceSize": {
      "x": 0,
      "y": 0,
      "w": 16,
      "h": 16
    },
    "sourceSize": {
      "w": 16,
      "h": 16
    }
  },
  {
    "filename": "grass_block_top.png",
    "frame": {
      "x": 127,
      "y": 1,
      "w": 16,
      "h": 16
    },
    "rotated": false,
    "trimmed": false,
    "spriteSourceSize": {
      "x": 0,
      "y": 0,
      "w": 16,
      "h": 16
    },
    "sourceSize": {
      "w": 16,
      "h": 16
    }
  },
  {
    "filename": "iron_ore.png",
    "frame": {
      "x": 145,
      "y": 1,
      "w": 16,
      "h": 16
    },
    "rotated": false,
    "trimmed": false,
    "spriteSourceSize": {
      "x": 0,
      "y": 0,
      "w": 16,
      "h": 16
    },
    "sourceSize": {
      "w": 16,
      "h": 16
    }
  },
  {
    "filename": "log_oak.png",
    "frame": {
      "x": 163,
      "y": 1,
      "w": 16,
      "h": 16
    },
    "rotated": false,
    "trimmed": false,
    "spriteSourceSize": {
      "x": 0,
      "y": 0,
      "w": 16,
      "h": 16
    },
    "sourceSize": {
      "w": 16,
      "h": 16
    }
  },
  {
    "filename": "log_oak_top.png",
    "frame": {
      "x": 181,
      "y": 1,
      "w": 16,
      "h": 16
    },
    "rotated": false,
    "trimmed": false,
    "spriteSourceSize": {
      "x": 0,
      "y": 0,
      "w": 16,
      "h": 16
    },
    "sourceSize": {
      "w": 16,
      "h": 16
    }
  },
  {
    "filename": "stone.png",
    "frame": {
      "x": 199,
      "y": 1,
      "w": 16,
      "h": 16
    },
    "rotated": false,
    "trimmed": false,
    "spriteSourceSize": {
      "x": 0,
      "y": 0,
      "w": 16,
      "h": 16
    },
    "sourceSize": {
      "w": 16,
      "h": 16
    }
  },
  {
    "filename": "oak_leaves.png",
    "frame": {
      "x": 217,
      "y": 1,
      "w": 16,
      "h": 16
    },
    "rotated": false,
    "trimmed": false,
    "spriteSourceSize": {
      "x": 0,
      "y": 0,
      "w": 16,
      "h": 16
    },
    "sourceSize": {
      "w": 16,
      "h": 16
    }
  }
];

export const meta = {
  "app": "scripts/build-atlas.mjs",
  "version": "1.0",
  "image": "asd.png",
  "format": "RGBA8888",
  "size": {
    "w": 234,
    "h": 18
  },
  "scale": "1"
};
