// Builds the block texture atlas (public/textures/blocks/asd.png) and its frame
// metadata (src/world/textureAtlas.js) from the individual 16x16 block PNGs.
//
// Layout: a single row of 16px tiles with 1px padding (18px stride, content at
// offset 1). Padding pixels are edge-extended so nearest-filter sampling never
// bleeds across tile boundaries. Grayscale textures (e.g. leaves) can be tinted.
//
// Run with: node scripts/build-atlas.mjs   (re-run when adding/changing blocks)

import { PNG } from 'pngjs';
import fs from 'fs';
import path from 'path';

const TILE = 16;
const PAD = 1;
const STRIDE = TILE + PAD; // 17? no - see below
const BLOCKS_DIR = 'public/textures/blocks';
const ATLAS_PATH = path.join(BLOCKS_DIR, 'asd.png');
const META_PATH = 'src/world/textureAtlas.js';

// Tile order. Keep the original 12 first so their atlas coords are unchanged;
// append new blocks. A string is an untinted tile; {file, tint} multiplies the
// (grayscale) texture by an [r,g,b] colour - used for biome-tinted foliage.
const TILES = [
  'bedrock.png',
  'coal_ore.png',
  'diamond_ore.png',
  'dirt_block.png',
  'gold_ore.png',
  'grass_block_side.png',
  'grass_block_side_snowed.png',
  'grass_block_top.png',
  'iron_ore.png',
  'log_oak.png',
  'log_oak_top.png',
  'stone.png',
  { file: 'oak_leaves.png', tint: [0x77, 0xab, 0x2f] }, // plains foliage green
];

const COL = TILE + 2 * PAD; // 18px per tile column (1px border each side)
const norm = TILES.map((t) => (typeof t === 'string' ? { file: t } : t));
const atlasW = norm.length * COL;
const atlasH = COL;

const atlas = new PNG({ width: atlasW, height: atlasH });
atlas.data.fill(0);

const setPx = (png, x, y, r, g, b, a) => {
  const i = (y * png.width + x) << 2;
  png.data[i] = r;
  png.data[i + 1] = g;
  png.data[i + 2] = b;
  png.data[i + 3] = a;
};
const getPx = (png, x, y) => {
  const i = (y * png.width + x) << 2;
  return [png.data[i], png.data[i + 1], png.data[i + 2], png.data[i + 3]];
};

const frames = [];

norm.forEach((tile, i) => {
  const src = PNG.sync.read(fs.readFileSync(path.join(BLOCKS_DIR, tile.file)));
  if (src.width !== TILE || src.height !== TILE) {
    throw new Error(`${tile.file} is ${src.width}x${src.height}, expected ${TILE}x${TILE}`);
  }

  const x0 = i * COL + PAD; // content origin
  const y0 = PAD;

  // Blit (with optional tint), then edge-extend by clamping into the padding.
  for (let py = -PAD; py < TILE + PAD; py++) {
    for (let px = -PAD; px < TILE + PAD; px++) {
      const sx = Math.min(TILE - 1, Math.max(0, px));
      const sy = Math.min(TILE - 1, Math.max(0, py));
      let [r, g, b, a] = getPx(src, sx, sy);
      if (tile.tint) {
        r = Math.round((r * tile.tint[0]) / 255);
        g = Math.round((g * tile.tint[1]) / 255);
        b = Math.round((b * tile.tint[2]) / 255);
      }
      setPx(atlas, x0 + px, y0 + py, r, g, b, a);
    }
  }

  frames.push({
    filename: tile.file,
    frame: { x: x0, y: y0, w: TILE, h: TILE },
    rotated: false,
    trimmed: false,
    spriteSourceSize: { x: 0, y: 0, w: TILE, h: TILE },
    sourceSize: { w: TILE, h: TILE },
  });
});

fs.writeFileSync(ATLAS_PATH, PNG.sync.write(atlas));

const meta = {
  app: 'scripts/build-atlas.mjs',
  version: '1.0',
  image: 'asd.png',
  format: 'RGBA8888',
  size: { w: atlasW, h: atlasH },
  scale: '1',
};

const js = `// AUTO-GENERATED by scripts/build-atlas.mjs - do not edit by hand.
export const frames = ${JSON.stringify(frames, null, 2)};

export const meta = ${JSON.stringify(meta, null, 2)};
`;
fs.writeFileSync(META_PATH, js);

console.log(`atlas: ${atlasW}x${atlasH}, ${frames.length} tiles -> ${ATLAS_PATH}, ${META_PATH}`);
